### ISSUE TITLE
Weird issue when combined with another module

### ISSUE THREAD

**Issue by linky00** [AdamMoses-GitHub/MMM-TwitterTrendsByPlace#1]
When I combine this module with https://github.com/SVendittelli/MMM-wordnik, it suddenly greatly expands in size. Here's a picture of that: http://imgur.com/a/MqKOd

What's up with this? Is it a css issue? Thanks!

**Comment by AdamMoses-GitHub** [comment]
It's a CSS issue. For whatever reason any of the columns (left, center, right) of the mirror layout will automatically expand width to the widest one. 

Your other module may be trying to use all available space, i.e. width: 100% or something like that. 

You can restrict the size of a given module, as I have done, but the header is populated by the mirror code, so trying to fix it's width doesn't seem possible, or at least easy.
